/**
 * imageBrowser.js — Right sidebar: scans an image directory,
 * renders thumbnails, supports drag to nav grid and search filter.
 */

export class ImageBrowser {
  /**
   * @param {HTMLElement} container - the #image-browser element
   * @param {import('./dataModel.js').TourMap} tourMap
   */
  constructor(container, tourMap) {
    this.container = container;
    this.tourMap = tourMap;
    /** @type {Map<string, string>} filename → object URL */
    this.imageMap = new Map();
    /** @type {Map<string, string>} lowercase filename → original filename key */
    this.imageMapLower = new Map();
    /** @type {Map<string, HTMLElement>} filename → thumbnail div */
    this.thumbMap = new Map();
    this.filterText = '';

    this.currentLightboxIndex = -1;
    this.displayedNames = [];
    this._setupLightbox();

    const searchInput = document.getElementById('image-search');
    if (searchInput) {
      searchInput.addEventListener('input', (e) => {
        this.filterText = e.target.value.toLowerCase();
        this.render();
      });
    }
  }

  _setupLightbox() {
    this.lightboxOverlay = document.getElementById('lightbox-overlay');
    this.lightboxImg = document.getElementById('lightbox-img');
    this.lightboxLabel = document.getElementById('lightbox-label');
    
    document.getElementById('btn-lightbox-close').addEventListener('click', () => this.closeLightbox());
    document.getElementById('btn-lightbox-prev').addEventListener('click', () => this.navigateLightbox(-1));
    document.getElementById('btn-lightbox-next').addEventListener('click', () => this.navigateLightbox(1));
    
    // Keyboard nav
    document.addEventListener('keydown', (e) => {
      if (!this.lightboxOverlay || this.lightboxOverlay.classList.contains('hidden')) return;
      if (e.key === 'Escape') this.closeLightbox();
      if (e.key === 'ArrowLeft') this.navigateLightbox(-1);
      if (e.key === 'ArrowRight') this.navigateLightbox(1);
    });
  }

  openLightbox(index) {
    if (index < 0 || index >= this.displayedNames.length) return;
    this.currentLightboxIndex = index;
    const name = this.displayedNames[index];
    const url = this.imageMap.get(name);
    
    this.lightboxImg.src = url;
    const photoId = this.extractIdFromFilename(name);
    this.lightboxLabel.textContent = photoId !== null ? `#${photoId} - ${name}` : name;
    
    this.lightboxOverlay.classList.remove('hidden');
  }

  closeLightbox() {
    this.lightboxOverlay.classList.add('hidden');
    this.lightboxImg.src = '';
  }

  navigateLightbox(direction) {
    let newIndex = this.currentLightboxIndex + direction;
    if (newIndex < 0) newIndex = this.displayedNames.length - 1;
    if (newIndex >= this.displayedNames.length) newIndex = 0;
    this.openLightbox(newIndex);
  }

  /**
   * Load images from a FileSystemDirectoryHandle (Chrome/Edge).
   * @param {FileSystemDirectoryHandle} dirHandle
   */
  async loadFromDirectoryHandle(dirHandle) {
    this.imageMap.clear();
    this.imageMapLower.clear();
    for await (const [name, handle] of dirHandle) {
      if (handle.kind === 'file' && /\.(jpg|jpeg|png|gif|webp)$/i.test(name)) {
        const file = await handle.getFile();
        const url = URL.createObjectURL(file);
        this.imageMap.set(name, url);
        this.imageMapLower.set(name.toLowerCase(), name);
      }
    }
    this.render();
  }

  /**
   * Load images from a FileList (Firefox fallback via webkitdirectory input).
   * @param {FileList} fileList
   */
  loadFromFileList(fileList) {
    this.imageMap.clear();
    this.imageMapLower.clear();
    for (const file of fileList) {
      if (/\.(jpg|jpeg|png|gif|webp)$/i.test(file.name)) {
        const url = URL.createObjectURL(file);
        let key = file.tourRelativePath || file.webkitRelativePath || file.name;
        // Normalize backslashes generated by webkitRelativePath
        key = key.replace(/\\/g, '/');
        
        // If the path starts with the loaded folder name (webkitRelativePath does this), strip it so it matches app expectations
        const parts = key.split('/');
        if (parts.length > 1 && fileList.length > 0) {
           // We can't easily know the root folder name to strip without tracking it, 
           // but `tourRelativePath` from app.js doesn't include the root folder.
           // So `key` is already cleanly relative like `history/DCP_0015.jpg`.
        }
        
        this.imageMap.set(key, url);
        this.imageMapLower.set(key.toLowerCase(), key);
      }
    }
    this.render();
  }

  /**
   * Get the object URL for a given filename (case-insensitive match).
   * @param {string} filename
   * @returns {string|null}
   */
  getImageUrl(filename) {
    // Try exact match first
    if (this.imageMap.has(filename)) return this.imageMap.get(filename);
    // Case-insensitive fallback
    const key = this.imageMapLower.get(filename.toLowerCase());
    if (key) return this.imageMap.get(key);
    
    // Fallback: If map is requesting "DCP_0015.jpg" but it's inside a folder like "images/DCP_0015.jpg"
    // and the map author forgot to specify the folder, we can guess by matching the basename.
    const baseTarget = filename.toLowerCase().split('/').pop();
    for (const [lowerKey, realKey] of this.imageMapLower.entries()) {
      if (lowerKey.split('/').pop() === baseTarget) {
        return this.imageMap.get(realKey);
      }
    }
    
    return null;
  }

  /**
   * Get the object URL for a photo ID using the tour's filename prefix.
   * @param {number} photoId
   * @returns {string|null}
   */
  getImageUrlById(photoId) {
    const entry = this.tourMap.findById(photoId);
    if (entry) {
      const fname = this.tourMap.getImageFilename(entry);
      return this.getImageUrl(fname);
    }
    // Fallback: try prefix + id + .jpg with extensions
    const prefix = this.tourMap.filenamePrefix || '';
    let idStr = String(photoId);
    if (this.tourMap.idPadding > 0 && /^\d+$/.test(idStr)) {
      idStr = idStr.padStart(this.tourMap.idPadding, '0');
    }
    
    const candidates = [
      prefix + idStr + '.jpg',
      prefix + idStr + '.JPG',
      prefix + idStr + '.jpeg',
      prefix + idStr + '.png',
    ];
    for (const c of candidates) {
      const url = this.getImageUrl(c);
      if (url) return url;
    }
    return null;
  }

  /**
   * Extract a photo ID from an image filename based on the current prefix.
   * @param {string} filename
   * @returns {number|null}
   */
  extractIdFromFilename(filename) {
    const prefix = this.tourMap.filenamePrefix || '';
    const baseName = filename.split('/').pop().replace(/\.[^.]+$/, ''); // remove path and extension
    if (prefix && baseName.startsWith(prefix)) {
      return baseName.substring(prefix.length);
    }
    // Try to extract trailing digits
    const match = baseName.match(/(\d+)$/);
    return match ? match[1] : null;
  }

  render() {
    this.container.innerHTML = '';
    this.thumbMap.clear();

    if (this.imageMap.size === 0) {
      this.container.innerHTML = '<div class="empty-state">Open an image folder</div>';
      return;
    }

    // Get set of used IDs
    const usedIds = new Set();
    for (const entry of this.tourMap.getLinkEntries()) {
      usedIds.add(entry.id);
    }

    // Sort filenames
    const sortedNames = [...this.imageMap.keys()].sort((a, b) =>
      a.localeCompare(b, undefined, { numeric: true })
    );

    this.displayedNames = [];

    for (const name of sortedNames) {
      if (this.filterText && !name.toLowerCase().includes(this.filterText)) continue;
      this.displayedNames.push(name);

      const url = this.imageMap.get(name);
      const photoId = this.extractIdFromFilename(name);

      const thumb = document.createElement('div');
      thumb.className = 'image-thumb';
      if (photoId !== null && usedIds.has(photoId)) {
        thumb.classList.add('used');
      }
      thumb.draggable = true;

      // Click to open lightbox
      const index = this.displayedNames.length - 1;
      thumb.addEventListener('click', () => {
        this.openLightbox(index);
      });

      thumb.addEventListener('dragstart', (e) => {
        if (photoId !== null) {
          e.dataTransfer.setData('application/photo-id', String(photoId));
        }
        e.dataTransfer.setData('application/image-name', name);
        e.dataTransfer.effectAllowed = 'link';
      });

      const img = document.createElement('img');
      img.src = url;
      img.alt = name;
      img.loading = 'lazy';
      thumb.appendChild(img);

      const label = document.createElement('div');
      label.className = 'thumb-label';
      label.textContent = name;
      thumb.appendChild(label);

      if (photoId !== null && usedIds.has(photoId)) {
        const idBadge = document.createElement('div');
        idBadge.className = 'thumb-id';
        idBadge.textContent = photoId;
        thumb.appendChild(idBadge);
      }

      this.thumbMap.set(name, thumb);
      this.container.appendChild(thumb);
    }
  }

  /**
   * Efficiently update "used" highlighting and badges without rebuilding the DOM.
   * Called on navigation and line edits.
   */
  refreshUsedStatus() {
    if (this.imageMap.size === 0 || this.thumbMap.size === 0) return;

    // Get set of currently used IDs
    const usedIds = new Set();
    for (const entry of this.tourMap.getLinkEntries()) {
      if (entry.id !== null) {
        usedIds.add(String(entry.id));
      }
    }

    for (const [name, thumb] of this.thumbMap) {
      const photoId = this.extractIdFromFilename(name);
      const isUsed = photoId !== null && usedIds.has(String(photoId));
      
      if (isUsed) {
        thumb.classList.add('used');
        if (!thumb.querySelector('.thumb-id')) {
          const idBadge = document.createElement('div');
          idBadge.className = 'thumb-id';
          idBadge.textContent = photoId;
          thumb.appendChild(idBadge);
        }
      } else {
        thumb.classList.remove('used');
        const badge = thumb.querySelector('.thumb-id');
        if (badge) badge.remove();
      }
    }
  }
}
